name: send_slack_notification
description: Send Slack notification
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  MESSAGE:
    description: 'Status message'
    required: true
runs:
  using: composite
  steps:
  - name: Send Slack Notification
    run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "${{ inputs.MESSAGE }}"
        }' \
          ${{ inputs.SLACK_WEBHOOK_URL }}
    shell: bash
